// Copyright 2020 ONIXLabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using OnixLabs.Core.Reflection;
using Xunit;

namespace OnixLabs.Core.UnitTests.Reflection;

public sealed class TypeExtensionTests
{
    [Theory(DisplayName = "Type.GetCSharpTypeDeclaration should produce the expected result")]
    [InlineData(typeof(byte), TypeDeclarationFlags.None, "Byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseAliasedTypeNames, "byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseGenericTypeArguments, "Byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseValueTupleSyntax, "Byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.UseValueTupleNames, "Byte")]
    [InlineData(typeof(byte), TypeDeclarationFlags.All, "byte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.None, "SByte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.SByte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseAliasedTypeNames, "sbyte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseNullableShorthandTypeNames, "SByte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "sbyte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseGenericTypeArguments, "SByte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseValueTupleSyntax, "SByte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.UseValueTupleNames, "SByte")]
    [InlineData(typeof(sbyte), TypeDeclarationFlags.All, "sbyte")]
    [InlineData(typeof(short), TypeDeclarationFlags.None, "Int16")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Int16")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseAliasedTypeNames, "short")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Int16")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "short")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseGenericTypeArguments, "Int16")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseValueTupleSyntax, "Int16")]
    [InlineData(typeof(short), TypeDeclarationFlags.UseValueTupleNames, "Int16")]
    [InlineData(typeof(short), TypeDeclarationFlags.All, "short")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.None, "UInt16")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.UInt16")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseAliasedTypeNames, "ushort")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UInt16")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ushort")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseGenericTypeArguments, "UInt16")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseValueTupleSyntax, "UInt16")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.UseValueTupleNames, "UInt16")]
    [InlineData(typeof(ushort), TypeDeclarationFlags.All, "ushort")]
    [InlineData(typeof(int), TypeDeclarationFlags.None, "Int32")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Int32")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseAliasedTypeNames, "int")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Int32")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "int")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseGenericTypeArguments, "Int32")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseValueTupleSyntax, "Int32")]
    [InlineData(typeof(int), TypeDeclarationFlags.UseValueTupleNames, "Int32")]
    [InlineData(typeof(int), TypeDeclarationFlags.All, "int")]
    [InlineData(typeof(uint), TypeDeclarationFlags.None, "UInt32")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.UInt32")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseAliasedTypeNames, "uint")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UInt32")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "uint")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseGenericTypeArguments, "UInt32")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseValueTupleSyntax, "UInt32")]
    [InlineData(typeof(uint), TypeDeclarationFlags.UseValueTupleNames, "UInt32")]
    [InlineData(typeof(uint), TypeDeclarationFlags.All, "uint")]
    [InlineData(typeof(long), TypeDeclarationFlags.None, "Int64")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Int64")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseAliasedTypeNames, "long")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Int64")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "long")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseGenericTypeArguments, "Int64")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseValueTupleSyntax, "Int64")]
    [InlineData(typeof(long), TypeDeclarationFlags.UseValueTupleNames, "Int64")]
    [InlineData(typeof(long), TypeDeclarationFlags.All, "long")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.None, "UInt64")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.UInt64")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseAliasedTypeNames, "ulong")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UInt64")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ulong")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseGenericTypeArguments, "UInt64")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseValueTupleSyntax, "UInt64")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.UseValueTupleNames, "UInt64")]
    [InlineData(typeof(ulong), TypeDeclarationFlags.All, "ulong")]
    [InlineData(typeof(nint), TypeDeclarationFlags.None, "IntPtr")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.IntPtr")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseAliasedTypeNames, "nint")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseNullableShorthandTypeNames, "IntPtr")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "nint")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseGenericTypeArguments, "IntPtr")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseValueTupleSyntax, "IntPtr")]
    [InlineData(typeof(nint), TypeDeclarationFlags.UseValueTupleNames, "IntPtr")]
    [InlineData(typeof(nint), TypeDeclarationFlags.All, "nint")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.None, "UIntPtr")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.UIntPtr")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseAliasedTypeNames, "nuint")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UIntPtr")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "nuint")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseGenericTypeArguments, "UIntPtr")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseValueTupleSyntax, "UIntPtr")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.UseValueTupleNames, "UIntPtr")]
    [InlineData(typeof(nuint), TypeDeclarationFlags.All, "nuint")]
    [InlineData(typeof(float), TypeDeclarationFlags.None, "Single")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Single")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseAliasedTypeNames, "float")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Single")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "float")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseGenericTypeArguments, "Single")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseValueTupleSyntax, "Single")]
    [InlineData(typeof(float), TypeDeclarationFlags.UseValueTupleNames, "Single")]
    [InlineData(typeof(float), TypeDeclarationFlags.All, "float")]
    [InlineData(typeof(double), TypeDeclarationFlags.None, "Double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseAliasedTypeNames, "double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseGenericTypeArguments, "Double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseValueTupleSyntax, "Double")]
    [InlineData(typeof(double), TypeDeclarationFlags.UseValueTupleNames, "Double")]
    [InlineData(typeof(double), TypeDeclarationFlags.All, "double")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.None, "Decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseAliasedTypeNames, "decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseGenericTypeArguments, "Decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseValueTupleSyntax, "Decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.UseValueTupleNames, "Decimal")]
    [InlineData(typeof(decimal), TypeDeclarationFlags.All, "decimal")]
    [InlineData(typeof(object), TypeDeclarationFlags.None, "Object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseAliasedTypeNames, "object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseGenericTypeArguments, "Object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseValueTupleSyntax, "Object")]
    [InlineData(typeof(object), TypeDeclarationFlags.UseValueTupleNames, "Object")]
    [InlineData(typeof(object), TypeDeclarationFlags.All, "object")]
    [InlineData(typeof(bool), TypeDeclarationFlags.None, "Boolean")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Boolean")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseAliasedTypeNames, "bool")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Boolean")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "bool")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseGenericTypeArguments, "Boolean")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseValueTupleSyntax, "Boolean")]
    [InlineData(typeof(bool), TypeDeclarationFlags.UseValueTupleNames, "Boolean")]
    [InlineData(typeof(bool), TypeDeclarationFlags.All, "bool")]
    [InlineData(typeof(char), TypeDeclarationFlags.None, "Char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseAliasedTypeNames, "char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseGenericTypeArguments, "Char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseValueTupleSyntax, "Char")]
    [InlineData(typeof(char), TypeDeclarationFlags.UseValueTupleNames, "Char")]
    [InlineData(typeof(char), TypeDeclarationFlags.All, "char")]
    [InlineData(typeof(string), TypeDeclarationFlags.None, "String")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.String")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseAliasedTypeNames, "string")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseNullableShorthandTypeNames, "String")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "string")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseGenericTypeArguments, "String")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseValueTupleSyntax, "String")]
    [InlineData(typeof(string), TypeDeclarationFlags.UseValueTupleNames, "String")]
    [InlineData(typeof(string), TypeDeclarationFlags.All, "string")]
    [InlineData(typeof(void), TypeDeclarationFlags.None, "Void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseAliasedTypeNames, "void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseGenericTypeArguments, "Void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseValueTupleSyntax, "Void")]
    [InlineData(typeof(void), TypeDeclarationFlags.UseValueTupleNames, "Void")]
    [InlineData(typeof(void), TypeDeclarationFlags.All, "void")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.None, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseAliasedTypeNames, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseGenericTypeArguments, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseValueTupleSyntax, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.UseValueTupleNames, "Guid")]
    [InlineData(typeof(Guid), TypeDeclarationFlags.All, "System.Guid")]
    [InlineData(typeof(Action), TypeDeclarationFlags.None, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseGenericTypeArguments, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseValueTupleSyntax, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.UseValueTupleNames, "Action")]
    [InlineData(typeof(Action), TypeDeclarationFlags.All, "System.Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.None, "Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseGenericTypeArguments, "Action<T>")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseValueTupleSyntax, "Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.UseValueTupleNames, "Action")]
    [InlineData(typeof(Action<>), TypeDeclarationFlags.All, "System.Action<T>")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.None, "ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseGenericTypeArguments, "ValueTuple<T1>")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseValueTupleSyntax, "ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.UseValueTupleNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<>), TypeDeclarationFlags.All, "System.ValueTuple<T1>")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.None, "IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseAliasedTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseGenericTypeArguments, "IEquatable<T>")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseValueTupleSyntax, "IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.UseValueTupleNames, "IEquatable")]
    [InlineData(typeof(IEquatable<>), TypeDeclarationFlags.All, "System.IEquatable<T>")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.None, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseGenericTypeArguments, "KeyValuePair<TKey, TValue>")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseValueTupleSyntax, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.UseValueTupleNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<,>), TypeDeclarationFlags.All, "System.Collections.Generic.KeyValuePair<TKey, TValue>")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.None, "List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseAliasedTypeNames, "List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseGenericTypeArguments, "List<T>")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseValueTupleSyntax, "List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.UseValueTupleNames, "List")]
    [InlineData(typeof(List<>), TypeDeclarationFlags.All, "System.Collections.Generic.List<T>")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.None, "Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseAliasedTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseGenericTypeArguments, "Dictionary<TKey, TValue>")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseValueTupleSyntax, "Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.UseValueTupleNames, "Dictionary")]
    [InlineData(typeof(Dictionary<,>), TypeDeclarationFlags.All, "System.Collections.Generic.Dictionary<TKey, TValue>")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.None, "Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseGenericTypeArguments, "Action<Int32>")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseValueTupleSyntax, "Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.UseValueTupleNames, "Action")]
    [InlineData(typeof(Action<int>), TypeDeclarationFlags.All, "System.Action<int>")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.None, "Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseGenericTypeArguments, "Action<Guid>")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseValueTupleSyntax, "Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.UseValueTupleNames, "Action")]
    [InlineData(typeof(Action<Guid>), TypeDeclarationFlags.All, "System.Action<System.Guid>")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.None, "ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseGenericTypeArguments, "ValueTuple<Int32>")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseValueTupleSyntax, "ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.UseValueTupleNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<int>), TypeDeclarationFlags.All, "System.ValueTuple<int>")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.None, "ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseGenericTypeArguments, "ValueTuple<Guid>")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseValueTupleSyntax, "ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.UseValueTupleNames, "ValueTuple")]
    [InlineData(typeof(ValueTuple<Guid>), TypeDeclarationFlags.All, "System.ValueTuple<System.Guid>")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.None, "IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseAliasedTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseGenericTypeArguments, "IEquatable<Int32>")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseValueTupleSyntax, "IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.UseValueTupleNames, "IEquatable")]
    [InlineData(typeof(IEquatable<int>), TypeDeclarationFlags.All, "System.IEquatable<int>")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.None, "IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseAliasedTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseGenericTypeArguments, "IEquatable<Guid>")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseValueTupleSyntax, "IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.UseValueTupleNames, "IEquatable")]
    [InlineData(typeof(IEquatable<Guid>), TypeDeclarationFlags.All, "System.IEquatable<System.Guid>")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.None, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseGenericTypeArguments, "KeyValuePair<String, Int32>")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseValueTupleSyntax, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.UseValueTupleNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, int>), TypeDeclarationFlags.All, "System.Collections.Generic.KeyValuePair<string, int>")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.None, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseGenericTypeArguments, "KeyValuePair<String, Guid>")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseValueTupleSyntax, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.UseValueTupleNames, "KeyValuePair")]
    [InlineData(typeof(KeyValuePair<string, Guid>), TypeDeclarationFlags.All, "System.Collections.Generic.KeyValuePair<string, System.Guid>")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.None, "List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseAliasedTypeNames, "List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseGenericTypeArguments, "List<Int32>")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseValueTupleSyntax, "List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.UseValueTupleNames, "List")]
    [InlineData(typeof(List<int>), TypeDeclarationFlags.All, "System.Collections.Generic.List<int>")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.None, "List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseAliasedTypeNames, "List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseGenericTypeArguments, "List<Guid>")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseValueTupleSyntax, "List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.UseValueTupleNames, "List")]
    [InlineData(typeof(List<Guid>), TypeDeclarationFlags.All, "System.Collections.Generic.List<System.Guid>")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.None, "Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseAliasedTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseGenericTypeArguments, "Dictionary<String, Int32>")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseValueTupleSyntax, "Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.UseValueTupleNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, int>), TypeDeclarationFlags.All, "System.Collections.Generic.Dictionary<string, int>")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.None, "Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Collections.Generic.Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseAliasedTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseGenericTypeArguments, "Dictionary<String, Guid>")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseValueTupleSyntax, "Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.UseValueTupleNames, "Dictionary")]
    [InlineData(typeof(Dictionary<string, Guid>), TypeDeclarationFlags.All, "System.Collections.Generic.Dictionary<string, System.Guid>")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.None, "ValueTuple")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.ValueTuple")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseGenericTypeArguments, "ValueTuple<String, Int32>")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseValueTupleSyntax, "(String, Int32)")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.UseValueTupleNames, "(String Item1, Int32 Item2)")]
    [InlineData(typeof((string, int)), TypeDeclarationFlags.All, "(string Item1, int Item2)")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.None, "ValueTuple")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.ValueTuple")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseGenericTypeArguments, "ValueTuple<String, Guid>")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseValueTupleSyntax, "(String, Guid)")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.UseValueTupleNames, "(String Item1, Guid Item2)")]
    [InlineData(typeof((string, Guid)), TypeDeclarationFlags.All, "(string Item1, System.Guid Item2)")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Byte?")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "byte?")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Byte>")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(byte?), TypeDeclarationFlags.All, "byte?")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "SByte?")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "sbyte?")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<SByte>")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(sbyte?), TypeDeclarationFlags.All, "sbyte?")]
    [InlineData(typeof(short?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Int16?")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "short?")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Int16>")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(short?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(short?), TypeDeclarationFlags.All, "short?")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UInt16?")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ushort?")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<UInt16>")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(ushort?), TypeDeclarationFlags.All, "ushort?")]
    [InlineData(typeof(int?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Int32?")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "int?")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Int32>")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(int?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(int?), TypeDeclarationFlags.All, "int?")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UInt32?")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "uint?")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<UInt32>")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(uint?), TypeDeclarationFlags.All, "uint?")]
    [InlineData(typeof(long?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Int64?")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "long?")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Int64>")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(long?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(long?), TypeDeclarationFlags.All, "long?")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UInt64?")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ulong?")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<UInt64>")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(ulong?), TypeDeclarationFlags.All, "ulong?")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "IntPtr?")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "nint?")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<IntPtr>")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(nint?), TypeDeclarationFlags.All, "nint?")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "UIntPtr?")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "nuint?")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<UIntPtr>")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(nuint?), TypeDeclarationFlags.All, "nuint?")]
    [InlineData(typeof(float?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Single?")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "float?")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Single>")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(float?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(float?), TypeDeclarationFlags.All, "float?")]
    [InlineData(typeof(double?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Double?")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "double?")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Double>")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(double?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(double?), TypeDeclarationFlags.All, "double?")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Decimal?")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "decimal?")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Decimal>")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(decimal?), TypeDeclarationFlags.All, "decimal?")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Boolean?")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "bool?")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Boolean>")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(bool?), TypeDeclarationFlags.All, "bool?")]
    [InlineData(typeof(char?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Char?")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "char?")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Char>")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(char?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(char?), TypeDeclarationFlags.All, "char?")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "Guid?")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "Guid?")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<Guid>")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(Guid?), TypeDeclarationFlags.All, "System.Guid?")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple?")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple?")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<ValueTuple>")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(ValueTuple?), TypeDeclarationFlags.All, "System.ValueTuple?")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple?")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple?")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<ValueTuple<Int32>>")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(ValueTuple<int>?), TypeDeclarationFlags.All, "System.ValueTuple<int>?")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple?")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple?")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<ValueTuple<Guid>>")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(ValueTuple<Guid>?), TypeDeclarationFlags.All, "System.ValueTuple<System.Guid>?")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "KeyValuePair?")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair?")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<KeyValuePair<String, Int32>>")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, int>?), TypeDeclarationFlags.All, "System.Collections.Generic.KeyValuePair<string, int>?")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "KeyValuePair?")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "KeyValuePair?")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<KeyValuePair<String, Guid>>")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof(KeyValuePair<string, Guid>?), TypeDeclarationFlags.All, "System.Collections.Generic.KeyValuePair<string, System.Guid>?")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple?")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple?")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<ValueTuple<String, Int32>>")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseValueTupleSyntax | TypeDeclarationFlags.UseNullableShorthandTypeNames, "(String, Int32)?")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.UseValueTupleNames | TypeDeclarationFlags.UseNullableShorthandTypeNames, "(String Item1, Int32 Item2)?")]
    [InlineData(typeof((string, int)?), TypeDeclarationFlags.All, "(string Item1, int Item2)?")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.None, "Nullable")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseNamespaceQualifiedTypeNames, "System.Nullable")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseAliasedTypeNames, "Nullable")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseNullableShorthandTypeNames, "ValueTuple?")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseNullableShorthandTypeNames | TypeDeclarationFlags.UseAliasedTypeNames, "ValueTuple?")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseGenericTypeArguments, "Nullable<ValueTuple<String, Guid>>")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseValueTupleSyntax, "Nullable")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseValueTupleSyntax | TypeDeclarationFlags.UseNullableShorthandTypeNames, "(String, Guid)?")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseValueTupleNames, "Nullable")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.UseValueTupleNames | TypeDeclarationFlags.UseNullableShorthandTypeNames, "(String Item1, Guid Item2)?")]
    [InlineData(typeof((string, Guid)?), TypeDeclarationFlags.All, "(string Item1, System.Guid Item2)?")]
    public void TypeGetCSharpTypeDeclarationShouldProduceExpectedResult(Type type, TypeDeclarationFlags flags, string expected)
    {
        // When
        string actual = type.GetCSharpTypeDeclaration(flags);

        // Then
        Assert.Equal(expected, actual);
    }
}
